### ISSUE TITLE
Move out all middlewares

### ISSUE THREAD

**Issue by umputun** [go-pkgz/jrpc#8]
Currently middleware selection is very opinionated and in some cases user may not like the provided set. Instead to hardcoding it will be better to allow injection of any middlewares user needs.

Probably some may stay mandatory, probably NoCache and Ping, but others (limiter, logger, recovery, throttler and RealIP) should be passed in.

**Comment by zebox** [comment]
Hi, I currently thinking fix this issue because i need use this package with custom middleware. I thinking add field to option with array of middleware func and pass it when service starting.
e.g.
```go
type middlewareFuncs []func(http.Handler) http.Handler

type Middlewares struct {
	items middlewareFuncs 
}

func New() *Middlewares{
	return &Middlewares{}
}

func(m *Middlewares) Add(fn func(http.Handler) http.Handler ) {
	m.items=append(m.items,fn)
}

func(m *Middlewares) GetAll() middlewareFuncs  {
	return m.items
}

... 

type Server struct {
       ...
	Middlewares middlewareFuncs
        ...
}
```

But I some confusing about you think remove mux from chi dependency, because new option will have to support  middlewares from different mux.

The most poplars muxers such as [chi](https://github.com/go-chi/chi/blob/master/chi.go#L72), [gorilla ](https://github.com/gorilla/mux/blob/master/middleware.go#L11)has the equal type of middleware func, but [gin ](https://github.com/gin-gonic/gin/blob/master/gin.go#L34)has different type of middleware func. 

I doubt that is good idea to support various http  muxer. Of course, for new middleware option will can implement as interface which will casting various middleware func to one type.

What are you think about it?

**Comment by umputun** [comment]
I don't see how middleware selection is related to the particular mux. All we care about is the standard `func(h http.Handler) http.Handler`, which should be working in any reasonable mux.  I'm not sure how do you plan to change the mux inside of this library and why? Btw, as you can see in the code, chi dependency was not removed and I closed the ticket after chi addressed the original problem.

Regarding middleware injection - all we need is a single method adding a list of middleware functions as direct injection.  I don't think we need the builder you proposed as all users need here is a direct setting of `CustomMilldewares` directly in the `jrpc.Server` struct init.

Probably, some of the current middlewares should be the default selection. Some others will have to stay no matter what user passes, for example,  `LimitHandler`, `Throttle` and `Recoverer`

**Comment by zebox** [comment]
Do you mean something like this?

```go

// server.go
type MiddlewareFuncs []func(http.Handler) http.Handler

type Server struct {
       ...
	CustomMilldewares middlewareFuncs
        ...
}

...
router.Use(s.CustomMiddleware...)
...

//  main.go
var myMiddleware MiddlewareFuncs 
myMiddleware=append(myMiddleware, auth.Auth)

srv:=jrpc.Server{
...
CustomMiddleware: myMiddleware,
...
}

```
Or best way add `Server` method for add custom middleware to struct settings?
